# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-16 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', tinymce.models.HTMLField(verbose_name='内容')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创作时间')),
                ('utime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('img', models.ImageField(blank=True, null=True, upload_to='static/upload/imgs')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('partner', models.CharField(max_length=255, verbose_name='好友',null=True,blank=True)),
                ('offer', models.CharField(max_length=255, verbose_name='好友申请',null=True,blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25, verbose_name='作者')),
                ('pwd', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('catime', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('age', models.PositiveIntegerField(default=18)),
                ('photo', models.ImageField(null=True, upload_to='static/upload/head')),
            ],
            managers=[
                ('usermanage', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='friends',
            name='oid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercol.Users'),
        ),
        migrations.AddField(
            model_name='articles',
            name='fid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercol.Users', verbose_name='作者'),
        ),
    ]
