# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-25 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('storename', models.CharField(max_length=20)),
                ('storephoto', models.ImageField(blank=True, upload_to='static/upload/store', validators=['店', '铺', '图', '片'])),
                ('reg_time', models.DateTimeField(auto_now_add=True, verbose_name='营业时间')),
                ('storeinfo', models.CharField(blank=True, max_length=100)),
                ('states', models.BooleanField(default=False, verbose_name='营业状态:')),
                ('masters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users')),
            ],
        ),
    ]
