# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-25 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adress', models.CharField(blank=True, max_length=100, verbose_name='地址')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pickname', models.CharField(max_length=20, verbose_name='昵称')),
                ('pwd', models.CharField(max_length=50, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('adress', models.CharField(blank=True, max_length=100, verbose_name='地址')),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('catime', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('header', models.ImageField(default='static/upload/head/header.png', upload_to='static/upload/head', verbose_name='头像')),
            ],
            managers=[
                ('usermanage', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='adfor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users'),
        ),
    ]
