# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-27 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cllocter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goodsid', models.IntegerField(verbose_name='商品id')),
                ('forcll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users')),
            ],
        ),
    ]
