# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-26 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='购物车状态')),
                ('forcar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goodname', models.CharField(max_length=30, verbose_name='商品名')),
                ('goodimg', models.CharField(max_length=255, verbose_name='商品图片')),
                ('gooodsize', models.CharField(default='L', max_length=52, verbose_name='商品尺码')),
                ('goodnum', models.IntegerField(verbose_name='数量')),
                ('goodprice', models.FloatField(verbose_name='单价')),
                ('goodid', models.IntegerField(verbose_name='商品id')),
                ('forord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Cars')),
            ],
        ),
        migrations.CreateModel(
            name='shoplist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goodnumnam', models.CharField(max_length=60, verbose_name='商品')),
                ('acount', models.FloatField(verbose_name='总额')),
                ('forord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users')),
            ],
        ),
    ]
